services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_tutormatch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ml:
    image: boikanyomohlax/ai-tutormatch-ml:latest
    restart: unless-stopped
    ports:
      - "5000:5000"

  backend:
    image: boikanyomohlax/ai-tutormatch-backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_tutormatch_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      ML_SERVICE_URL: http://ml:5000

  frontend:
    image: boikanyomohlax/ai-tutormatch-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
