services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_tutormatch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml:
    build:
      context: ./AI-TutorMatch-ML
      dockerfile: Dockerfile
    container_name: ai-ml
    ports:
      - "5000:5000"
    restart: unless-stopped

  backend:
    build:
      context: ./ai-tutormatch
      dockerfile: Dockerfile   # must be the one starting with FROM eclipse-temurin:21-jdk
    container_name: ai-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_tutormatch_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      ML_SERVICE_URL: http://ml:5000
    restart: unless-stopped

  frontend:
    build:
      context: ./ai-tutormatch-ui
      dockerfile: Dockerfile
    container_name: ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
