package com.tut.ai_tutormatch.enums;

public enum Specialization {
    ARTIFICIAL_INTELLIGENCE,
    MACHINE_LEARNING,
    DATA_SCIENCE,
    SOFTWARE_ENGINEERING,
    CYBER_SECURITY,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATABASE_SYSTEMS,
    COMPUTER_NETWORKS,
    CLOUD_COMPUTING,
    DEVOPS,
    COMPUTER_SCIENCE
}
